import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

group = "app.anlage.site"
version = "0.0.1-SNAPSHOT"


plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    kotlin("jvm") version "2.4.10"
    //kotlin("kapt") version "1.3.20"
    // io.ratpack.ratpack-java removed: every release of it calls the `compile`
    // configuration, which Gradle dropped in 7.0. This project never used
    // ratpack directly -- it arrives transitively via dc2f-edit-api, which now
    // declares ratpack-core itself.

    // Apply the application plugin to add support for building a CLI application.
    application
}

tasks.withType<KotlinCompile> {
    // kotlinOptions was removed in Kotlin 2.2; compilerOptions replaces it, and
    // -Xjvm-default became -jvm-default ("no-compatibility" == the old "all").
    compilerOptions {
        freeCompilerArgs.add("-jvm-default=no-compatibility")
    }
}

// Pins both the Java and Kotlin targets together, and must sit after the
// plugins block since `kotlin { }` is an extension the Kotlin plugin adds.
kotlin {
    jvmToolchain(17)
}

allprojects {
    repositories {
        // jcenter() dropped: shut down in 2021 and removed in Gradle 9.
        mavenCentral()
        maven("https://jitpack.io")
        maven("https://oss.sonatype.org/content/groups/public/")
    }
}
//
//sourceSets {
//    main {
//        resources {
//            srcDir("web/content")
//        }
//    }
//}

repositories {
    // jcenter() dropped: shut down in 2021 and removed in Gradle 9.
    mavenCentral()
}

dependencies {
    //kapt("com.github.therapi:therapi-runtime-javadoc-scribe:0.9.0")
    //compile("com.github.therapi:therapi-runtime-javadoc:0.9.0")

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.1")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.3.1")
//    implementation(project("dc2f"))
    //implementation("com.dc2f:dc2f:0.0.1-SNAPSHOT")
    //implementation("com.dc2f:dc2f:master-SNAPSHOT")
    implementation("com.dc2f:dc2f:0.1.3-SNAPSHOT")

    implementation("io.github.microutils:kotlin-logging:1.4.9")

    // utils
    implementation("org.apache.commons:commons-text:1.6")
    implementation("org.apache.commons:commons-lang3:3.8.1")
    implementation("commons-io:commons-io:2.6")


    implementation("com.dc2f:dc2f-common:+")



    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

// The RatpackContinuousRun block that lived here went with the plugin. It only
// set flattenClassloaders for `gradle -t run`, i.e. `dc2f.sh serve`. The server
// still watches web/content itself, so content edits reload as before; a change
// to Kotlin sources now needs a restart.

application {
    // Define the main class for the application.
    // mainClassName was removed in Gradle 8.
    mainClass.set("app.authpass.website.WebsiteKt")
//    applicationDefaultJvmArgs =
//      listOf("--add-opens java.base/java.lang=ALL-UNNAMED",
//        "--add-opens java.base/java.util=ALL-UNNAMED")
}

